# Generated by Django 5.2.7 on 2025-12-16 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoKhau',
            fields=[
                ('id_hokhau', models.AutoField(primary_key=True, serialize=False)),
                ('so_can_ho', models.CharField(max_length=20)),
                ('dien_tich', models.FloatField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'hokhau',
            },
        ),
        migrations.CreateModel(
            name='KhoanThu',
            fields=[
                ('id_khoanthu', models.IntegerField(primary_key=True, serialize=False)),
                ('ten_khoanthu', models.CharField(max_length=100)),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('don_vi_tinh', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'khoanthu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VaiTro',
            fields=[
                ('id_vaitro', models.IntegerField(primary_key=True, serialize=False)),
                ('ten_vaitro', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vaitro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DotThuPhi',
            fields=[
                ('id_dotthu', models.IntegerField(primary_key=True, serialize=False)),
                ('ten_dotthu', models.CharField(max_length=100)),
                ('ngay_batdau', models.DateField()),
                ('ngay_ketthuc', models.DateField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('draft', 'Nháp'), ('open', 'Mở'), ('closed', 'Đóng')], default='draft', max_length=6)),
                ('id_khoanthu', models.ForeignKey(db_column='id_khoanthu', default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='dot_thus', to='core.khoanthu')),
            ],
            options={
                'db_table': 'dotthuphi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NhanKhau',
            fields=[
                ('id_nhankhau', models.IntegerField(primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cccd', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('quan_he_chu_ho', models.CharField(blank=True, max_length=50, null=True)),
                ('id_hokhau', models.ForeignKey(db_column='id_hokhau', default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='nhan_khaus', to='core.hokhau')),
            ],
            options={
                'db_table': 'nhankhau',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BienDongNhanKhau',
            fields=[
                ('id_biendong', models.IntegerField(primary_key=True, serialize=False)),
                ('loai_biendong', models.CharField(choices=[('tam_tru', 'Tạm trú'), ('tam_vang', 'Tạm vắng')], max_length=8)),
                ('ngay_batdau', models.DateField()),
                ('ngay_ketthuc', models.DateField(blank=True, null=True)),
                ('ly_do', models.TextField(blank=True, null=True)),
                ('id_nhankhau', models.ForeignKey(db_column='id_nhankhau', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nhankhau', to='core.nhankhau')),
            ],
            options={
                'db_table': 'biendongnhankhau',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_taikhoan', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('vaitro', models.ForeignKey(db_column='id_vaitro', on_delete=django.db.models.deletion.CASCADE, related_name='vaitro', to='core.vaitro')),
            ],
            options={
                'db_table': 'taikhoan',
            },
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id_hoadon', models.IntegerField(primary_key=True, serialize=False)),
                ('tong_tien', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ngay_nop', models.DateField(blank=True, null=True)),
                ('id_dotthu', models.ForeignKey(db_column='id_dotthu', default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='hoa_dons', to='core.dotthuphi')),
                ('id_hokhau', models.ForeignKey(db_column='id_hokhau', default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='hoa_dons', to='core.hokhau')),
            ],
            options={
                'db_table': 'hoadon',
                'managed': True,
                'indexes': [models.Index(fields=['id_hokhau'], name='idx_hoadon_hokhau'), models.Index(fields=['id_dotthu'], name='idx_hoadon_dotthu')],
                'constraints': [models.UniqueConstraint(fields=('id_hokhau', 'id_dotthu'), name='uq_hoadon_hokhau_dotthu')],
            },
        ),
        migrations.AddIndex(
            model_name='dotthuphi',
            index=models.Index(fields=['id_khoanthu'], name='idx_dotthu_khoanthu'),
        ),
        migrations.AddIndex(
            model_name='nhankhau',
            index=models.Index(fields=['id_hokhau'], name='id_hokhau'),
        ),
    ]
