# Generated by Django 5.2.7 on 2025-12-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
