# Generated by Django 5.2.7 on 2025-12-16 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_taikhoan_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='vaitro',
            field=models.ForeignKey(blank=True, db_column='id_vaitro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaitro', to='core.vaitro'),
        ),
    ]
