# Generated by Django 5.2.7 on 2026-01-03 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_taikhoan_vaitro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biendongnhankhau",
            name="id_biendong",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="biendongnhankhau",
            name="id_nhankhau",
            field=models.ForeignKey(
                db_column="id_nhankhau",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biendongs",
                to="core.nhankhau",
            ),
        ),
        migrations.AlterField(
            model_name="biendongnhankhau",
            name="loai_biendong",
            field=models.CharField(
                choices=[
                    ("tam_tru", "Tạm trú"),
                    ("tam_vang", "Tạm vắng"),
                    ("thuong_tru", "Thường trú"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dotthuphi",
            name="id_khoanthu",
            field=models.ForeignKey(
                db_column="id_khoanthu",
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="dot_thuphi",
                to="core.khoanthu",
            ),
        ),
        migrations.AlterField(
            model_name="hoadon",
            name="id_hoadon",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="khoanthu",
            name="don_vi_tinh",
            field=models.CharField(
                choices=[
                    ("m2", "Mét vuông(m²)"),
                    ("nguoi", "Người"),
                    ("ho", "Hộ gia đình"),
                    ("thang", "Tháng"),
                    ("nam", "Năm"),
                    ("luot", "Lượt"),
                ],
                default="nguoi",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="nhankhau",
            name="id_hokhau",
            field=models.ForeignKey(
                db_column="id_hokhau",
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="ho_khau",
                to="core.hokhau",
            ),
        ),
        migrations.AlterField(
            model_name="nhankhau",
            name="id_nhankhau",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="vaitro",
            name="id_vaitro",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
