# Generated by Django 4.2.29 on 2026-04-05 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_biendongnhankhau_id_biendong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biendongnhankhau',
            name='id_nhankhau',
            field=models.ForeignKey(db_column='id_nhankhau', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nhankhau', to='core.nhankhau'),
        ),
        migrations.AlterField(
            model_name='biendongnhankhau',
            name='loai_biendong',
            field=models.CharField(choices=[('tam_tru', 'Tạm trú'), ('tam_vang', 'Tạm vắng'), ('thuong_tru', 'Thường trú')], max_length=12),
        ),
        migrations.AlterField(
            model_name='dotthuphi',
            name='trang_thai',
            field=models.CharField(choices=[('open', 'Mở'), ('closed', 'Đóng')], default='open', max_length=6),
        ),
        migrations.AlterField(
            model_name='khoanthu',
            name='don_vi_tinh',
            field=models.CharField(choices=[('nguoi', 'Người'), ('ho', 'Hộ gia đình'), ('thang', 'Tháng'), ('nam', 'Năm'), ('luot', 'Lượt')], default='nguoi', max_length=20),
        ),
    ]
