# Generated by Django 4.2.29 on 2026-04-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_biendongnhankhau_id_nhankhau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khoanthu',
            name='phi_bat_buoc',
            field=models.BooleanField(default=True),
        ),
    ]
