# Generated by Django 4.2.29 on 2026-04-07 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_khoanthu_phi_bat_buoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khoanthu',
            name='id_khoanthu',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
