# Generated by Django 4.2.30 on 2026-04-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_khoanthu_id_khoanthu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khoanthu',
            name='don_vi_tinh',
            field=models.CharField(choices=[('nguoi', 'Người'), ('ho', 'Hộ gia đình'), ('thang', 'Tháng'), ('nam', 'Năm'), ('luot', 'Lượt'), ('dientich', 'Diện tích (m2)')], default='nguoi', max_length=20),
        ),
    ]
