# Generated by Django 4.2.30 on 2026-04-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_khoanthu_don_vi_tinh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khoanthu',
            name='don_gia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
