# Generated by Django 4.2.30 on 2026-04-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_biendongnhankhau_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dotthuphi',
            name='idx_dotthu_khoanthu',
        ),
        migrations.RemoveField(
            model_name='dotthuphi',
            name='id_khoanthu',
        ),
        migrations.AddField(
            model_name='dotthuphi',
            name='id_khoanthu',
            field=models.ManyToManyField(blank=True, db_table='dotthuphi_khoanthu', related_name='dot_thuphi', to='core.khoanthu'),
        ),
    ]
