# Generated by Django 4.2.30 on 2026-04-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_dotthuphi_idx_dotthu_khoanthu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotthuphi',
            name='loai_dot_thu',
            field=models.CharField(choices=[('dinh_ky', 'Định kỳ'), ('bo_sung', 'Bổ sung'), ('tu_nguyen', 'Tự nguyện'), ('khac', 'Khác')], default='dinh_ky', max_length=20),
        ),
    ]
