# Generated by Django 4.2.30 on 2026-04-14 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dotthuphi_loai_dot_thu'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDonChiTiet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('so_luong', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thanh_tien', models.DecimalField(decimal_places=2, max_digits=15)),
                ('hoadon', models.ForeignKey(db_column='id_hoadon', on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiets', to='core.hoadon')),
                ('khoanthu', models.ForeignKey(db_column='id_khoanthu', on_delete=django.db.models.deletion.RESTRICT, related_name='chitiet_hoadons', to='core.khoanthu')),
            ],
            options={
                'db_table': 'hoadon_chitiet',
                'managed': True,
            },
        ),
    ]
