# Generated by Django 4.2.30 on 2026-04-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_hoadonchitiet'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='channel',
            field=models.CharField(choices=[('tien_mat', 'Tiền mặt'), ('chuyen_khoan', 'Chuyển khoản'), ('khac', 'Khác')], default='tien_mat', max_length=20),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='da_dong',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
