# Generated by Django 4.2.30 on 2026-04-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_hoadon_channel_hoadon_da_dong'),
    ]

    operations = [
        migrations.AddField(
            model_name='taikhoan',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='create_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
