# Generated by Django 4.2.30 on 2026-04-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_taikhoan_create_at_taikhoan_create_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhankhau',
            name='quan_he_chu_ho',
            field=models.CharField(blank=True, choices=[('chu_ho', 'Chủ hộ'), ('vo_chong', 'Vợ/chồng'), ('cha_me', 'Cha/mẹ'), ('anh_chi_em', 'Anh/chị/em'), ('con', 'Con'), ('ong_ba', 'Ông/bà'), ('nguoi_giam_ho', 'Người giám hộ'), ('o_thue_o_nho', 'Ở thuê/ Ở nhờ'), ('khac', 'Khác')], max_length=20, null=True),
        ),
    ]
