# Generated by Django 4.2.30 on 2026-04-29 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_nhankhau_quan_he_chu_ho'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhankhau',
            name='id_taikhoan',
            field=models.ForeignKey(blank=True, db_column='id_taikhoan', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tai_khoan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nhankhau',
            name='is_chu_ho',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='biendongnhankhau',
            name='id_nhankhau',
            field=models.ForeignKey(db_column='id_nhankhau', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nhan_khau', to='core.nhankhau'),
        ),
        migrations.AlterField(
            model_name='nhankhau',
            name='id_hokhau',
            field=models.ForeignKey(blank=True, db_column='id_hokhau', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ho_khau', to='core.hokhau'),
        ),
        migrations.AddConstraint(
            model_name='nhankhau',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_chu_ho', True), ('quan_he_chu_ho', 'chu_ho')), fields=('id_hokhau',), name='unique_active_chu_ho_per_hokhau'),
        ),
    ]
