# Generated by Django 4.2.30 on 2026-04-29 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_nhankhau_id_taikhoan_nhankhau_is_chu_ho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='id_taikhoan',
            field=models.ForeignKey(blank=True, db_column='id_taikhoan', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='acc_hoadon', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nhankhau',
            name='id_taikhoan',
            field=models.ForeignKey(blank=True, db_column='id_taikhoan', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='acc_nhankhau', to=settings.AUTH_USER_MODEL),
        ),
    ]
