# Generated by Django 4.2.30 on 2026-05-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_hoadon_id_taikhoan_alter_nhankhau_id_taikhoan'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaitro',
            name='display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
