# Generated by Django 4.2.30 on 2026-05-10 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_vaitro_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanHo',
            fields=[
                ('id_canho', models.AutoField(primary_key=True, serialize=False)),
                ('so_can_ho', models.CharField(max_length=20)),
                ('dien_tich', models.FloatField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'canho',
            },
        ),
        migrations.RemoveField(
            model_name='hoadon',
            name='id_taikhoan',
        ),
        migrations.RemoveField(
            model_name='hokhau',
            name='dien_tich',
        ),
        migrations.RemoveField(
            model_name='hokhau',
            name='so_can_ho',
        ),
        migrations.RemoveField(
            model_name='nhankhau',
            name='id_taikhoan',
        ),
        migrations.AddField(
            model_name='hokhau',
            name='id_chuho',
            field=models.ForeignKey(blank=True, db_column='id_chuho', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='chu_ho', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hokhau',
            name='id_canho',
            field=models.ForeignKey(blank=True, db_column='id_canho', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='can_ho', to='core.canho'),
        ),
    ]
