# Generated by Django 4.2.30 on 2026-05-13 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_canho_remove_hoadon_id_taikhoan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Tên tòa nhà')),
                ('max_floor', models.PositiveIntegerField(verbose_name='Số tầng tối đa')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'building',
            },
        ),
        migrations.AddField(
            model_name='canho',
            name='apartment_type',
            field=models.CharField(blank=True, choices=[('studio', 'Studio'), ('1pn', '1 Phòng ngủ'), ('2pn', '2 Phòng ngủ'), ('3pn', '3 Phòng ngủ'), ('khac', 'Khác')], max_length=20, null=True, verbose_name='Loại căn hộ'),
        ),
        migrations.AddField(
            model_name='canho',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tầng'),
        ),
        migrations.AddField(
            model_name='canho',
            name='status',
            field=models.CharField(blank=True, choices=[('dang_o', 'Đang ở'), ('de_trong', 'Để trống'), ('cho_thue', 'Cho thuê'), ('khac', 'Khác')], max_length=20, null=True, verbose_name='Trạng thái sử dụng'),
        ),
        migrations.AddField(
            model_name='hokhau',
            name='resident_status',
            field=models.CharField(blank=True, choices=[('thuong_tru', 'Thường trú'), ('tam_tru', 'Tạm trú'), ('khac', 'Khác')], max_length=20, null=True, verbose_name='Tình trạng cư trú'),
        ),
        migrations.AddField(
            model_name='canho',
            name='building',
            field=models.ForeignKey(blank=True, db_column='building_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='canhos', to='core.building', verbose_name='Tòa nhà'),
        ),
    ]
