# Generated by Django 4.2.30 on 2026-05-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_building_canho_apartment_type_canho_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canho',
            name='dien_tich',
            field=models.FloatField(blank=True, null=True, verbose_name='Diện tích'),
        ),
        migrations.AlterField(
            model_name='canho',
            name='so_can_ho',
            field=models.CharField(max_length=20, verbose_name='Số căn hộ'),
        ),
    ]
