# Generated by Django 4.2.30 on 2026-05-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_canho_dien_tich_alter_canho_so_can_ho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canho',
            name='status',
            field=models.CharField(choices=[('dang_o', 'Đang ở'), ('de_trong', 'Để trống'), ('cho_thue', 'Cho thuê'), ('khac', 'Khác')], default='de_trong', max_length=20, verbose_name='Trạng thái sử dụng'),
        ),
    ]
