# Generated by Django 4.2.30 on 2026-05-17 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_canho_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hokhau',
            name='id_canho',
            field=models.ForeignKey(db_column='id_canho', on_delete=django.db.models.deletion.RESTRICT, related_name='can_ho', to='core.canho'),
        ),
        migrations.AlterField(
            model_name='hokhau',
            name='id_chuho',
            field=models.ForeignKey(db_column='id_chuho', on_delete=django.db.models.deletion.RESTRICT, related_name='chu_ho', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hokhau',
            name='resident_status',
            field=models.CharField(choices=[('thuong_tru', 'Thường trú'), ('tam_tru', 'Tạm trú'), ('de_trong', 'Để trống'), ('khac', 'Khác')], default='de_trong', max_length=20, verbose_name='Tình trạng cư trú'),
        ),
    ]
