# Generated by Django 4.2.30 on 2026-05-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_hokhau_id_canho_alter_hokhau_id_chuho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhankhau',
            name='gioi_tinh',
            field=models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], default='O', max_length=1),
        ),
    ]
