# Generated by Django 4.2.30 on 2026-05-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_nhankhau_gioi_tinh'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hokhau',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('id_canho', 'id_chuho'), name='unique_canho_chuho_not_deleted'),
        ),
    ]
