# Generated by Django 4.2.30 on 2026-05-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_hokhau_unique_canho_chuho_not_deleted'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='canho',
            constraint=models.UniqueConstraint(fields=('so_can_ho',), name='unique_so_can_ho'),
        ),
    ]
