# Generated by Django 4.2.30 on 2026-05-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_canho_unique_so_can_ho'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhankhau',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='nhankhau',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
