# Generated by Django 4.2.30 on 2026-05-17 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_nhankhau_email_nhankhau_so_dien_thoai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhankhau',
            name='cccd',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CCCD phải gồm 12 chữ số.', regex='^\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='nhankhau',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải bắt đầu bằng 0 và gồm 10 chữ số.', regex='^0\\d{9}$')]),
        ),
    ]
