# Generated by Django 4.2.30 on 2026-05-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_nhankhau_cccd_alter_nhankhau_so_dien_thoai'),
    ]

    operations = [
        migrations.AddField(
            model_name='biendongnhankhau',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
