# Generated by Django 4.2.30 on 2026-05-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_biendongnhankhau_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hokhau',
            name='resident_status',
            field=models.CharField(choices=[('thuong_tru', 'Thường trú'), ('tam_tru', 'Tạm trú'), ('tam_vang', 'Tạm vắng'), ('khac', 'Khác')], default='tam_vang', max_length=20, verbose_name='Tình trạng cư trú'),
        ),
    ]
