# Generated by Django 4.2.30 on 2026-05-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_hokhau_resident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biendongnhankhau',
            name='loai_biendong',
            field=models.CharField(choices=[('tam_tru', 'Tạm trú'), ('tam_vang', 'Tạm vắng'), ('thuong_tru', 'Thường trú'), ('cham_dut', 'Chấm dứt cư trú')], max_length=12),
        ),
    ]
