# Generated by Django 4.2.30 on 2026-05-19 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_biendongnhankhau_loai_biendong'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiXe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_xe', models.CharField(choices=[('xe_dap', 'Xe đạp'), ('xe_may', 'Xe máy'), ('o_to', 'Ô tô')], max_length=10)),
                ('bien_so', models.CharField(blank=True, max_length=20, null=True)),
                ('mo_ta', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('hokhau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guixe', to='core.hokhau')),
            ],
            options={
                'verbose_name': 'Gửi xe',
                'verbose_name_plural': 'Gửi xe',
            },
        ),
    ]
