# Generated by Django 4.2.30 on 2026-05-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_thongbao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khoanthu',
            name='don_vi_tinh',
            field=models.CharField(choices=[('nguoi', 'Người'), ('ho', 'Hộ gia đình'), ('thang', 'Tháng'), ('nam', 'Năm'), ('luot', 'Lượt'), ('dientich', 'Diện tích (m2)'), ('xe_may', 'Xe máy'), ('oto', 'Ô tô'), ('xe_dap', 'Xe đạp')], default='nguoi', max_length=20),
        ),
    ]
